
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/daslab/.cache/JetBrains/RemoteDev/dist/d665901452acc_CLion-2023.2/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Linux - 4.15.0-211-generic - x86_64
...
